{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================================================\n",
      "QURAN WORD-BY-WORD ALIGNMENT\n",
      "============================================================\n",
      "\n",
      "=== SYSTEM CHECK ===\n",
      "GPU: NVIDIA GeForce RTX 4080\n",
      "Total GPU Memory: 15.99GB\n",
      "Currently Used: 0.00GB\n",
      "Reserved: 0.00GB\n",
      "Free: 15.99GB\n",
      "✓ Sufficient GPU memory available\n",
      "Cleared CUDA cache\n",
      "\n",
      "=== FILE DETECTION ===\n",
      "✓ Audio: bakara.mp3\n",
      "✓ Text: baqara.txt\n",
      "\n",
      "Will create:\n",
      "  - bakara_whisper_raw.json\n",
      "  - bakara_timings.json\n",
      "\n",
      "Audio file size: 3.10MB\n",
      "Audio sample rate: 16000Hz\n",
      "\n",
      "============================================================\n"
     ]
    }
   ],
   "source": [
    "# BLOCK 1: AUTO-DETECT FILES + GPU CHECK\n",
    "import os\n",
    "import json\n",
    "from pathlib import Path\n",
    "from rapidfuzz import fuzz\n",
    "import re\n",
    "import torch\n",
    "\n",
    "print(\"=\"*60)\n",
    "print(\"QURAN WORD-BY-WORD ALIGNMENT\")\n",
    "print(\"=\"*60)\n",
    "\n",
    "# GPU Check\n",
    "print(\"\\n=== SYSTEM CHECK ===\")\n",
    "if torch.cuda.is_available():\n",
    "    print(f\"GPU: {torch.cuda.get_device_name(0)}\")\n",
    "    total_mem = torch.cuda.get_device_properties(0).total_memory / 1024**3\n",
    "    allocated = torch.cuda.memory_allocated() / 1024**3\n",
    "    reserved = torch.cuda.memory_reserved() / 1024**3\n",
    "    free = total_mem - reserved\n",
    "    \n",
    "    print(f\"Total GPU Memory: {total_mem:.2f}GB\")\n",
    "    print(f\"Currently Used: {allocated:.2f}GB\")\n",
    "    print(f\"Reserved: {reserved:.2f}GB\")\n",
    "    print(f\"Free: {free:.2f}GB\")\n",
    "    \n",
    "    if free < 4.0:\n",
    "        print(\"⚠ WARNING: Less than 4GB free! May need CPU mode.\")\n",
    "    else:\n",
    "        print(\"✓ Sufficient GPU memory available\")\n",
    "    \n",
    "    # Clear any existing allocations\n",
    "    torch.cuda.empty_cache()\n",
    "    print(\"Cleared CUDA cache\")\n",
    "else:\n",
    "    print(\"No GPU detected - will use CPU\")\n",
    "\n",
    "# Find files\n",
    "print(\"\\n=== FILE DETECTION ===\")\n",
    "audio_files = list(Path(\".\").glob(\"*.mp3\")) + list(Path(\".\").glob(\"*.wav\"))\n",
    "if not audio_files:\n",
    "    raise FileNotFoundError(\"No audio file found!\")\n",
    "audio_file = str(audio_files[0])\n",
    "\n",
    "text_files = list(Path(\".\").glob(\"*.txt\"))\n",
    "if not text_files:\n",
    "    raise FileNotFoundError(\"No text file found!\")\n",
    "text_file = str(text_files[0])\n",
    "\n",
    "base_name = Path(audio_file).stem\n",
    "output_json = f\"{base_name}_timings.json\"\n",
    "whisper_raw = f\"{base_name}_whisper_raw.json\"\n",
    "\n",
    "print(f\"✓ Audio: {audio_file}\")\n",
    "print(f\"✓ Text: {text_file}\")\n",
    "print(f\"\\nWill create:\")\n",
    "print(f\"  - {whisper_raw}\")\n",
    "print(f\"  - {output_json}\")\n",
    "\n",
    "# Check audio file size\n",
    "audio_size = os.path.getsize(audio_file) / 1024**2\n",
    "print(f\"\\nAudio file size: {audio_size:.2f}MB\")\n",
    "\n",
    "# Estimate processing requirements\n",
    "import librosa\n",
    "y, sr = librosa.load(audio_file, sr=16000, duration=1)  # Just load 1s to check\n",
    "print(f\"Audio sample rate: {sr}Hz\")\n",
    "del y  # Clean up\n",
    "\n",
    "print(\"\\n\" + \"=\"*60)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "STEP 1: WHISPER TRANSCRIPTION\n",
      "============================================================\n",
      "\n",
      "✓ Using existing (APPROVED): bakara_whisper_raw.json\n",
      "   (Delete this file to re-transcribe)\n",
      "\n",
      "📊 Whisper: 150 words\n"
     ]
    }
   ],
   "source": [
    "# BLOCK 2: WHISPER TRANSCRIPTION WITH PROGRESS & GPU MONITORING\n",
    "print(\"\\n\" + \"=\"*60)\n",
    "print(\"STEP 1: WHISPER TRANSCRIPTION\")\n",
    "print(\"=\"*60)\n",
    "\n",
    "from faster_whisper import WhisperModel\n",
    "from tqdm import tqdm\n",
    "import torch\n",
    "\n",
    "# GPU Monitoring function\n",
    "def print_gpu_usage():\n",
    "    if torch.cuda.is_available():\n",
    "        gpu_mem = torch.cuda.memory_allocated() / 1024**3\n",
    "        gpu_max = torch.cuda.max_memory_allocated() / 1024**3\n",
    "        gpu_reserved = torch.cuda.memory_reserved() / 1024**3\n",
    "        print(f\"  GPU Memory: {gpu_mem:.2f}GB used | {gpu_max:.2f}GB peak | {gpu_reserved:.2f}GB reserved\")\n",
    "    else:\n",
    "        print(\"  CPU mode (no GPU)\")\n",
    "\n",
    "if os.path.exists(whisper_raw):\n",
    "    print(f\"\\n✓ Using existing (APPROVED): {whisper_raw}\")\n",
    "    print(\"   (Delete this file to re-transcribe)\")\n",
    "    with open(whisper_raw, 'r', encoding='utf-8') as f:\n",
    "        whisper_words = json.load(f)\n",
    "else:\n",
    "    print(f\"\\n⚠️  {whisper_raw} not found - will transcribe\")\n",
    "    print(\"\\nLoading Whisper model...\")\n",
    "    \n",
    "    # Clear CUDA cache\n",
    "    if torch.cuda.is_available():\n",
    "        torch.cuda.empty_cache()\n",
    "        print(\"Cleared CUDA cache\")\n",
    "    \n",
    "    print_gpu_usage()\n",
    "    \n",
    "    # Use smaller model or CPU if GPU memory is limited\n",
    "    try:\n",
    "        model = WhisperModel(\"large-v2\", device=\"cuda\", compute_type=\"float16\")\n",
    "        print(\"Loaded large-v2 model on GPU\")\n",
    "    except Exception as e:\n",
    "        print(f\"GPU failed ({e}), falling back to CPU...\")\n",
    "        model = WhisperModel(\"large-v2\", device=\"cpu\", compute_type=\"int8\")\n",
    "    \n",
    "    print_gpu_usage()\n",
    "    \n",
    "    print(f\"\\nTranscribing: {audio_file}\")\n",
    "    print(\"This may take several minutes...\")\n",
    "    \n",
    "    # Get audio duration for progress bar\n",
    "    import librosa\n",
    "    y, sr = librosa.load(audio_file, sr=16000)\n",
    "    duration = len(y) / sr\n",
    "    print(f\"Audio duration: {duration:.1f}s\")\n",
    "    \n",
    "    # Transcribe with progress tracking\n",
    "    segments_generator, info = model.transcribe(\n",
    "        audio_file,\n",
    "        language=\"ar\",\n",
    "        word_timestamps=True,\n",
    "        beam_size=5,\n",
    "        best_of=5,\n",
    "        temperature=0.0\n",
    "    )\n",
    "    \n",
    "    print(f\"Detected language: {info.language} (probability: {info.language_probability:.2f})\")\n",
    "    \n",
    "    # Process segments with progress bar\n",
    "    whisper_words = []\n",
    "    segment_count = 0\n",
    "    \n",
    "    with tqdm(total=int(duration), desc=\"Transcribing\", unit=\"s\") as pbar:\n",
    "        for segment in segments_generator:\n",
    "            segment_count += 1\n",
    "            for word in segment.words:\n",
    "                whisper_words.append({\n",
    "                    \"word\": word.word.strip(),\n",
    "                    \"start_ms\": int(word.start * 1000),\n",
    "                    \"end_ms\": int(word.end * 1000)\n",
    "                })\n",
    "            \n",
    "            # Update progress bar\n",
    "            pbar.update(int(segment.end - segment.start))\n",
    "            \n",
    "            # Show GPU usage every 10 segments\n",
    "            if segment_count % 10 == 0:\n",
    "                print_gpu_usage()\n",
    "    \n",
    "    print(f\"\\nProcessed {segment_count} segments, found {len(whisper_words)} words\")\n",
    "    print_gpu_usage()\n",
    "    \n",
    "    # Save\n",
    "    with open(whisper_raw, 'w', encoding='utf-8') as f:\n",
    "        json.dump(whisper_words, f, ensure_ascii=False, indent=2)\n",
    "    print(f\"✓ Saved: {whisper_raw}\")\n",
    "    \n",
    "    # Clear GPU memory after transcription\n",
    "    if torch.cuda.is_available():\n",
    "        del model\n",
    "        torch.cuda.empty_cache()\n",
    "        print(\"\\nCleared GPU memory\")\n",
    "        print_gpu_usage()\n",
    "\n",
    "print(f\"\\n📊 Whisper: {len(whisper_words)} words\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "STEP 2: ANCHOR-BASED ALIGNMENT\n",
      "============================================================\n",
      "✓ Skipped Basmala\n",
      "\n",
      "Quran: 200 words | Whisper: 150 words\n",
      "\n",
      "🔍 Finding all possible matches...\n",
      "\n",
      "⚓ Finding anchor points...\n",
      "Found 163 anchor points (≥80% confidence)\n",
      "  Anchor 0: Q[0]='الٓمٓ' ↔ W[47] (score: 86%)\n",
      "  Anchor 1: Q[1]='ذَٰلِكَ' ↔ W[6] (score: 100%)\n",
      "  Anchor 2: Q[2]='ٱلۡكِتَٰبُ' ↔ W[7] (score: 80%)\n",
      "  Anchor 3: Q[3]='لَا' ↔ W[8] (score: 100%)\n",
      "  Anchor 4: Q[4]='رَيۡبَۛ' ↔ W[9] (score: 100%)\n",
      "\n",
      "🔗 Interpolating between anchors...\n",
      "  Segment 0: Q[0→0] ↔ W[4→47]\n",
      "  Segment 1: Q[0→1] ↔ W[47→6]\n",
      "  Segment 2: Q[1→2] ↔ W[6→7]\n",
      "  Segment 3: Q[2→3] ↔ W[7→8]\n",
      "  Segment 4: Q[3→4] ↔ W[8→9]\n",
      "  Segment 5: Q[4→5] ↔ W[9→10]\n",
      "  Segment 6: Q[5→6] ↔ W[10→11]\n",
      "  Segment 7: Q[6→7] ↔ W[11→12]\n",
      "  Segment 8: Q[7→8] ↔ W[12→13]\n",
      "  Segment 9: Q[8→9] ↔ W[13→14]\n",
      "  Segment 10: Q[9→10] ↔ W[14→15]\n",
      "  Segment 11: Q[10→11] ↔ W[15→16]\n",
      "  Segment 12: Q[11→13] ↔ W[16→18]\n",
      "  Segment 13: Q[13→14] ↔ W[18→19]\n",
      "  Segment 14: Q[14→15] ↔ W[19→20]\n",
      "  Segment 15: Q[15→16] ↔ W[20→21]\n",
      "  Segment 16: Q[16→17] ↔ W[21→14]\n",
      "  Segment 17: Q[17→18] ↔ W[14→23]\n",
      "  Segment 18: Q[18→19] ↔ W[23→24]\n",
      "  Segment 19: Q[19→20] ↔ W[24→25]\n",
      "  Segment 20: Q[20→21] ↔ W[25→26]\n",
      "  Segment 21: Q[21→22] ↔ W[26→24]\n",
      "  Segment 22: Q[22→23] ↔ W[24→28]\n",
      "  Segment 23: Q[23→24] ↔ W[28→29]\n",
      "  Segment 24: Q[24→25] ↔ W[29→30]\n",
      "  Segment 25: Q[25→26] ↔ W[30→31]\n",
      "  Segment 26: Q[26→27] ↔ W[31→32]\n",
      "  Segment 27: Q[27→28] ↔ W[32→33]\n",
      "  Segment 28: Q[28→29] ↔ W[33→34]\n",
      "  Segment 29: Q[29→30] ↔ W[34→11]\n",
      "  Segment 30: Q[30→31] ↔ W[11→28]\n",
      "  Segment 31: Q[31→32] ↔ W[28→37]\n",
      "  Segment 32: Q[32→33] ↔ W[37→38]\n",
      "  Segment 33: Q[33→34] ↔ W[38→31]\n",
      "  Segment 34: Q[34→35] ↔ W[31→40]\n",
      "  Segment 35: Q[35→36] ↔ W[40→41]\n",
      "  Segment 36: Q[36→37] ↔ W[41→13]\n",
      "  Segment 37: Q[37→38] ↔ W[13→43]\n",
      "  Segment 38: Q[38→39] ↔ W[43→44]\n",
      "  Segment 39: Q[39→40] ↔ W[44→45]\n",
      "  Segment 40: Q[40→41] ↔ W[45→46]\n",
      "  Segment 41: Q[41→42] ↔ W[46→47]\n",
      "  Segment 42: Q[42→43] ↔ W[47→48]\n",
      "  Segment 43: Q[43→44] ↔ W[48→49]\n",
      "  Segment 44: Q[44→45] ↔ W[49→8]\n",
      "  Segment 45: Q[45→46] ↔ W[8→14]\n",
      "  Segment 46: Q[46→47] ↔ W[14→52]\n",
      "  Segment 47: Q[47→48] ↔ W[52→53]\n",
      "  Segment 48: Q[48→49] ↔ W[53→34]\n",
      "  Segment 49: Q[49→50] ↔ W[34→55]\n",
      "  Segment 50: Q[50→51] ↔ W[55→56]\n",
      "  Segment 51: Q[51→52] ↔ W[56→57]\n",
      "  Segment 52: Q[52→53] ↔ W[57→56]\n",
      "  Segment 53: Q[53→54] ↔ W[56→59]\n",
      "  Segment 54: Q[54→55] ↔ W[59→60]\n",
      "  Segment 55: Q[55→56] ↔ W[60→61]\n",
      "  Segment 56: Q[56→57] ↔ W[61→62]\n",
      "  Segment 57: Q[57→58] ↔ W[62→63]\n",
      "  Segment 58: Q[58→59] ↔ W[63→64]\n",
      "  Segment 59: Q[59→60] ↔ W[64→65]\n",
      "  Segment 60: Q[60→61] ↔ W[65→28]\n",
      "  Segment 61: Q[61→62] ↔ W[28→67]\n",
      "  Segment 62: Q[62→63] ↔ W[67→68]\n",
      "  Segment 63: Q[63→64] ↔ W[68→69]\n",
      "  Segment 64: Q[64→65] ↔ W[69→70]\n",
      "  Segment 65: Q[65→66] ↔ W[70→71]\n",
      "  Segment 66: Q[66→67] ↔ W[71→26]\n",
      "  Segment 67: Q[67→68] ↔ W[26→31]\n",
      "  Segment 68: Q[68→69] ↔ W[31→74]\n",
      "  Segment 69: Q[69→70] ↔ W[74→80]\n",
      "  Segment 70: Q[70→71] ↔ W[80→53]\n",
      "  Segment 71: Q[71→72] ↔ W[53→21]\n",
      "  Segment 72: Q[72→73] ↔ W[21→78]\n",
      "  Segment 73: Q[73→74] ↔ W[78→26]\n",
      "  Segment 74: Q[74→75] ↔ W[26→80]\n",
      "  Segment 75: Q[75→76] ↔ W[80→81]\n",
      "  Segment 76: Q[76→77] ↔ W[81→82]\n",
      "  Segment 77: Q[77→78] ↔ W[82→26]\n",
      "  Segment 78: Q[78→79] ↔ W[26→84]\n",
      "  Segment 79: Q[79→80] ↔ W[84→85]\n",
      "  Segment 80: Q[80→81] ↔ W[85→55]\n",
      "  Segment 81: Q[81→82] ↔ W[55→87]\n",
      "  Segment 82: Q[82→83] ↔ W[87→88]\n",
      "  Segment 83: Q[83→84] ↔ W[88→53]\n",
      "  Segment 84: Q[84→85] ↔ W[53→90]\n",
      "  Segment 85: Q[85→86] ↔ W[90→61]\n",
      "  Segment 86: Q[86→87] ↔ W[61→62]\n",
      "  Segment 87: Q[87→88] ↔ W[62→93]\n",
      "  Segment 88: Q[88→89] ↔ W[93→23]\n",
      "  Segment 89: Q[89→90] ↔ W[23→95]\n",
      "  Segment 90: Q[90→91] ↔ W[95→96]\n",
      "  Segment 91: Q[91→92] ↔ W[96→97]\n",
      "  Segment 92: Q[92→93] ↔ W[97→98]\n",
      "  Segment 93: Q[93→94] ↔ W[98→99]\n",
      "  Segment 94: Q[94→95] ↔ W[99→8]\n",
      "  Segment 95: Q[95→96] ↔ W[8→101]\n",
      "  Segment 96: Q[96→97] ↔ W[101→85]\n",
      "  Segment 97: Q[97→98] ↔ W[85→103]\n",
      "  Segment 98: Q[98→99] ↔ W[103→104]\n",
      "  Segment 99: Q[99→100] ↔ W[104→105]\n",
      "  Segment 100: Q[100→101] ↔ W[105→106]\n",
      "  Segment 101: Q[101→102] ↔ W[106→107]\n",
      "  Segment 102: Q[102→103] ↔ W[107→81]\n",
      "  Segment 103: Q[103→104] ↔ W[81→109]\n",
      "  Segment 104: Q[104→105] ↔ W[109→31]\n",
      "  Segment 105: Q[105→106] ↔ W[31→111]\n",
      "  Segment 106: Q[106→107] ↔ W[111→112]\n",
      "  Segment 107: Q[107→108] ↔ W[112→8]\n",
      "  Segment 108: Q[108→109] ↔ W[8→84]\n",
      "  Segment 109: Q[109→110] ↔ W[84→97]\n",
      "  Segment 110: Q[110→111] ↔ W[97→98]\n",
      "  Segment 111: Q[111→112] ↔ W[98→99]\n",
      "  Segment 112: Q[112→113] ↔ W[99→78]\n",
      "  Segment 113: Q[113→114] ↔ W[78→119]\n",
      "  Segment 114: Q[114→115] ↔ W[119→120]\n",
      "  Segment 115: Q[115→116] ↔ W[120→65]\n",
      "  Segment 116: Q[116→117] ↔ W[65→104]\n",
      "  Segment 117: Q[117→118] ↔ W[104→123]\n",
      "  Segment 118: Q[118→119] ↔ W[123→119]\n",
      "  Segment 119: Q[119→120] ↔ W[119→120]\n",
      "  Segment 120: Q[120→121] ↔ W[120→126]\n",
      "  Segment 121: Q[121→122] ↔ W[126→81]\n",
      "  Segment 122: Q[122→123] ↔ W[81→109]\n",
      "  Segment 123: Q[123→124] ↔ W[109→31]\n",
      "  Segment 124: Q[124→125] ↔ W[31→126]\n",
      "  Segment 125: Q[125→126] ↔ W[126→112]\n",
      "  Segment 126: Q[126→127] ↔ W[112→8]\n",
      "  Segment 127: Q[127→128] ↔ W[8→133]\n",
      "  Segment 128: Q[128→129] ↔ W[133→97]\n",
      "  Segment 129: Q[129→130] ↔ W[97→135]\n",
      "  Segment 130: Q[130→131] ↔ W[135→13]\n",
      "  Segment 131: Q[131→132] ↔ W[13→78]\n",
      "  Segment 132: Q[132→133] ↔ W[78→104]\n",
      "  Segment 133: Q[133→134] ↔ W[104→68]\n",
      "  Segment 134: Q[134→135] ↔ W[68→97]\n",
      "  Segment 135: Q[135→136] ↔ W[97→141]\n",
      "  Segment 136: Q[136→137] ↔ W[141→142]\n",
      "  Segment 137: Q[137→138] ↔ W[142→143]\n",
      "  Segment 138: Q[138→139] ↔ W[143→104]\n",
      "  Segment 139: Q[139→140] ↔ W[104→145]\n",
      "  Segment 140: Q[140→141] ↔ W[145→146]\n",
      "  Segment 141: Q[141→142] ↔ W[146→105]\n",
      "  Segment 142: Q[142→143] ↔ W[105→106]\n",
      "  Segment 143: Q[143→144] ↔ W[106→149]\n",
      "  Segment 144: Q[144→145] ↔ W[149→53]\n",
      "  Segment 145: Q[145→147] ↔ W[53→37]\n",
      "  Segment 146: Q[147→149] ↔ W[37→85]\n",
      "  Segment 147: Q[149→151] ↔ W[85→133]\n",
      "  Segment 148: Q[151→152] ↔ W[133→33]\n",
      "  Segment 149: Q[152→153] ↔ W[33→13]\n",
      "  Segment 150: Q[153→160] ↔ W[13→26]\n",
      "  Segment 151: Q[160→161] ↔ W[26→95]\n",
      "  Segment 152: Q[161→170] ↔ W[95→23]\n",
      "  Segment 153: Q[170→173] ↔ W[23→53]\n",
      "  Segment 154: Q[173→176] ↔ W[53→85]\n",
      "  Segment 155: Q[176→178] ↔ W[85→8]\n",
      "  Segment 156: Q[178→183] ↔ W[8→31]\n",
      "  Segment 157: Q[183→184] ↔ W[31→8]\n",
      "  Segment 158: Q[184→188] ↔ W[8→28]\n",
      "  Segment 159: Q[188→190] ↔ W[28→10]\n",
      "  Segment 160: Q[190→194] ↔ W[10→133]\n",
      "  Segment 161: Q[194→196] ↔ W[133→85]\n",
      "  Segment 162: Q[196→198] ↔ W[85→28]\n",
      "  Segment 163: Q[198→200] ↔ W[28→150]\n",
      "\n",
      "✅ Aligned 200 words\n",
      "\n",
      "📊 Sample alignments:\n",
      "  [0] 'الٓمٓ' 72180ms to 72580ms (400ms)\n",
      "  [1] 'ذَٰلِكَ' 13580ms to 15540ms (1960ms)\n",
      "  [2] 'ٱلۡكِتَٰبُ' 14540ms to 15960ms (1420ms)\n",
      "  [50] 'قُلُوبِهِمۡ' 79760ms to 81760ms (2000ms)\n",
      "  [100] 'إِنَّمَا' 139920ms to 142920ms (3000ms)\n",
      "  [150] 'طُغۡيَٰنِهِمۡ' 147820ms to 182300ms (34480ms)\n",
      "  [198] 'مِّنَ' 45200ms to 125120ms (79920ms)\n",
      "  [199] 'ٱلصَّوَٰعِقِ' 124380ms to 201480ms (77100ms)\n"
     ]
    }
   ],
   "source": [
    "# BLOCK 3: ANCHOR-BASED ALIGNMENT\n",
    "print(\"\\n\" + \"=\"*60)\n",
    "print(\"STEP 2: ANCHOR-BASED ALIGNMENT\")\n",
    "print(\"=\"*60)\n",
    "\n",
    "def normalize_arabic(text):\n",
    "    \"\"\"Strip everything except base letters\"\"\"\n",
    "    text = re.sub(r'[^\\u0621-\\u063A\\u0641-\\u064A]', '', text)\n",
    "    text = text.replace('أ', 'ا').replace('إ', 'ا').replace('آ', 'ا').replace('ٱ', 'ا')\n",
    "    text = text.replace('ة', 'ه').replace('ى', 'ي').replace('ؤ', 'و').replace('ئ', 'ي')\n",
    "    return text\n",
    "\n",
    "with open(text_file, 'r', encoding='utf-8') as f:\n",
    "    quran_text = f.read()\n",
    "\n",
    "quran_text = re.sub(r'\\s*\\(\\d+\\)\\s*', ' ', quran_text)\n",
    "all_quran_words = quran_text.split()\n",
    "word_limit = len(whisper_words) + 50\n",
    "quran_words = all_quran_words[:word_limit]\n",
    "\n",
    "whisper_normalized = [normalize_arabic(w['word']) for w in whisper_words]\n",
    "quran_normalized = [normalize_arabic(w) for w in quran_words]\n",
    "\n",
    "# Skip Basmala\n",
    "whisper_start = 0\n",
    "basmala_norm = [normalize_arabic(w) for w in ['بسم', 'الله', 'الرحمن', 'الرحيم']]\n",
    "if len(whisper_words) >= 4:\n",
    "    if [whisper_normalized[i] for i in range(4)] == basmala_norm:\n",
    "        if normalize_arabic(quran_words[0]) != basmala_norm[0]:\n",
    "            whisper_start = 4\n",
    "            print(\"✓ Skipped Basmala\")\n",
    "\n",
    "print(f\"\\nQuran: {len(quran_words)} words | Whisper: {len(whisper_words)} words\")\n",
    "\n",
    "# STEP 1: Find ALL possible matches with scores\n",
    "print(\"\\n🔍 Finding all possible matches...\")\n",
    "matches = []  # (q_idx, w_idx, num_combined, score)\n",
    "\n",
    "for q_idx in range(len(quran_words)):\n",
    "    q_norm = quran_normalized[q_idx]\n",
    "    best_for_this_q = None\n",
    "    \n",
    "    for w_idx in range(whisper_start, len(whisper_words)):\n",
    "        for num_combine in range(1, min(7, len(whisper_words) - w_idx + 1)):\n",
    "            combined = \"\".join(whisper_normalized[w_idx:w_idx + num_combine])\n",
    "            score = fuzz.ratio(q_norm, combined)\n",
    "            \n",
    "            if not best_for_this_q or score > best_for_this_q[3]:\n",
    "                best_for_this_q = (q_idx, w_idx, num_combine, score)\n",
    "    \n",
    "    if best_for_this_q:\n",
    "        matches.append(best_for_this_q)\n",
    "\n",
    "# STEP 2: Find ANCHORS (high confidence matches)\n",
    "print(\"\\n⚓ Finding anchor points...\")\n",
    "anchors = []\n",
    "for q_idx, w_idx, num_combine, score in matches:\n",
    "    if score >= 80:  # High confidence\n",
    "        anchors.append((q_idx, w_idx, num_combine, score))\n",
    "\n",
    "anchors.sort(key=lambda x: x[0])  # Sort by Quran index\n",
    "print(f\"Found {len(anchors)} anchor points (≥80% confidence)\")\n",
    "\n",
    "# Show anchors\n",
    "for i in range(min(5, len(anchors))):\n",
    "    q_idx, w_idx, num_combine, score = anchors[i]\n",
    "    print(f\"  Anchor {i}: Q[{q_idx}]='{quran_words[q_idx]}' ↔ W[{w_idx}] (score: {score:.0f}%)\")\n",
    "\n",
    "# STEP 3: Interpolate between anchors\n",
    "print(\"\\n🔗 Interpolating between anchors...\")\n",
    "aligned = []\n",
    "\n",
    "if not anchors:\n",
    "    print(\"❌ No anchors found! Using best guesses...\")\n",
    "    # Fallback: use all matches\n",
    "    for q_idx, w_idx, num_combine, score in matches:\n",
    "        if w_idx + num_combine - 1 < len(whisper_words):\n",
    "            aligned.append({\n",
    "                \"word\": quran_words[q_idx],\n",
    "                \"start_ms\": whisper_words[w_idx][\"start_ms\"],\n",
    "                \"end_ms\": whisper_words[w_idx + num_combine - 1][\"end_ms\"]\n",
    "            })\n",
    "else:\n",
    "    # Add start anchor (beginning)\n",
    "    anchors.insert(0, (0, whisper_start, 1, 100))\n",
    "    # Add end anchor\n",
    "    anchors.append((len(quran_words), len(whisper_words), 1, 100))\n",
    "    \n",
    "    # Process each segment between anchors\n",
    "    for i in range(len(anchors) - 1):\n",
    "        anchor1_q, anchor1_w, _, _ = anchors[i]\n",
    "        anchor2_q, anchor2_w, _, _ = anchors[i + 1]\n",
    "        \n",
    "        quran_gap = anchor2_q - anchor1_q\n",
    "        whisper_gap = anchor2_w - anchor1_w\n",
    "        \n",
    "        print(f\"  Segment {i}: Q[{anchor1_q}→{anchor2_q}] ↔ W[{anchor1_w}→{anchor2_w}]\")\n",
    "        \n",
    "        if quran_gap == 0:\n",
    "            continue\n",
    "        \n",
    "        # Proportionally distribute Whisper words\n",
    "        for j in range(quran_gap):\n",
    "            q_idx = anchor1_q + j\n",
    "            if q_idx >= len(quran_words):\n",
    "                break\n",
    "            \n",
    "            # Calculate proportional Whisper position\n",
    "            ratio = j / quran_gap if quran_gap > 0 else 0\n",
    "            w_start_idx = anchor1_w + int(ratio * whisper_gap)\n",
    "            w_end_idx = anchor1_w + int((j + 1) / quran_gap * whisper_gap)\n",
    "            \n",
    "            # Ensure valid indices\n",
    "            w_start_idx = max(whisper_start, min(w_start_idx, len(whisper_words) - 1))\n",
    "            w_end_idx = max(w_start_idx, min(w_end_idx, len(whisper_words) - 1))\n",
    "            \n",
    "            if w_start_idx < len(whisper_words) and w_end_idx < len(whisper_words):\n",
    "                aligned.append({\n",
    "                    \"word\": quran_words[q_idx],\n",
    "                    \"start_ms\": whisper_words[w_start_idx][\"start_ms\"],\n",
    "                    \"end_ms\": whisper_words[w_end_idx][\"end_ms\"]\n",
    "                })\n",
    "\n",
    "print(f\"\\n✅ Aligned {len(aligned)} words\")\n",
    "\n",
    "# Show samples\n",
    "print(\"\\n📊 Sample alignments:\")\n",
    "for i in [0, 1, 2, len(aligned)//4, len(aligned)//2, len(aligned)*3//4, len(aligned)-2, len(aligned)-1]:\n",
    "    if 0 <= i < len(aligned):\n",
    "        w = aligned[i]\n",
    "        dur = w['end_ms'] - w['start_ms']\n",
    "        print(f\"  [{i}] '{w['word']}' {w['start_ms']}ms to {w['end_ms']}ms ({dur}ms)\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "STEP 3: SAVING\n",
      "============================================================\n",
      "\n",
      "Saved: bakara_timings.json\n",
      "\n",
      "DONE! Use in HTML:\n",
      "  1. Upload audio: bakara.mp3\n",
      "  2. Upload JSON: bakara_timings.json\n",
      "  3. Upload text: baqara.txt\n"
     ]
    }
   ],
   "source": [
    "# BLOCK 4: SAVE OUTPUT\n",
    "print(\"\\n\" + \"=\"*60)\n",
    "print(\"STEP 3: SAVING\")\n",
    "print(\"=\"*60)\n",
    "\n",
    "with open(output_json, 'w', encoding='utf-8') as f:\n",
    "    json.dump(aligned, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "print(f\"\\nSaved: {output_json}\")\n",
    "print(f\"\\nDONE! Use in HTML:\")\n",
    "print(f\"  1. Upload audio: {audio_file}\")\n",
    "print(f\"  2. Upload JSON: {output_json}\")\n",
    "print(f\"  3. Upload text: {text_file}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "hai",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
